apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authors
#  labels:
#    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      name: authors-v1
    spec:
      containers:
      - image: docker.io/haraldu/authors:1
        env:
        - name: DATABASE
          value: 'local'
        - name: CLOUDANT_URL
          value: ''

